---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: credentials
spec:
  secretStoreRef:
    name: doppler-prep
    kind: ClusterSecretStore
  data:
    - remoteRef:
        key: PYPI_ACCESS_FILE
        decodingStrategy: Base64
      secretKey: access_file

