---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: credentials
spec:
  secretStoreRef:
    name: scaleway-prep-pypi
    kind: ClusterSecretStore
  data:
    - secretKey: access_file
      remoteRef:
        key: "name:access-file"
        decodingStrategy: None
