# docker pull :1.69.2
---
{{- with .Values.backup }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup
spec:
  suspend: {{ not .enabled }}
  schedule: {{ .schedule | quote }}
  timeZone: {{ .timeZone | quote }}
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 3
  startingDeadlineSeconds: 1200
  jobTemplate:
    spec:
      backoffLimit: 0
      activeDeadlineSeconds: 7200
      template:
        spec:
          restartPolicy: Never
          serviceAccountName: pypi
          securityContext:
            fsGroup: 9898
            runAsGroup: 9898
            runAsUser: 9898
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          affinity:
            podAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - topologyKey: kubernetes.io/hostname
                  labelSelector:
                    matchLabels:
                      app: pypi
          containers:
            - name: rclone
              image: {{ .image.repository }}:{{ .image.tag }}
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop: [ALL]
                readOnlyRootFilesystem: true
              args:
                - "sync"
                - "--update"
                - "--fast-list"
                - "--use-server-modtime"
                - "--retries=1"
                - "/data/"
                - "s3:/"
              resources:
                requests: {{ .resources | toJson }}
                limits: {{ .resources | toJson }}
              volumeMounts:
                - mountPath: /config/rclone
                  name: config
                  readOnly: true
                - mountPath: /data
                  name: data
                  readOnly: true
          volumes:
            - name: config
              secret:
                secretName: backup
            - name: data
              persistentVolumeClaim:
                claimName: pypi-data-pypi-0
                readOnly: true
{{- end }}
