---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backup
spec:
  secretStoreRef:
    name: scaleway-prep-pypi
    kind: ClusterSecretStore
  target:
    template:
      engineVersion: v2
      data:
        rclone.conf: |
          [s3-insecure]
          type = s3
          provider = Scaleway
          endpoint = {{ `{{ .s3Endpoint }}` }}
          region = {{ `{{ .s3Region }}` }}
          access_key_id = {{ `{{ .s3AccessKey }}` }}
          secret_access_key = {{ `{{ .s3SecretKey }}` }}

          [s3]
          type = crypt
          remote = s3-insecure:
          password = {{ `{{ .encryptionPassword }}` }}
          directory_name_encryption = true
  dataFrom:
    - extract:
        key: "name:backup"
