apiVersion: v1
kind: Service
metadata:
  name: pypi
spec:
  selector:
    app: pypi
  ports:
    - port: 80
      name: http
      protocol: TCP
      targetPort: http
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pypi
  labels:
    app: pypi
spec:
  selector:
    matchLabels:
      app: pypi
  serviceName: pypi
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: pypi-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  template:
    metadata:
      labels:
        app: pypi
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: bjoernpetersen.net/location
                    operator: In
                    values:
                      - europe
      imagePullSecrets:
        - name: github
      volumes:
        - name: credentials
          secret:
            secretName: credentials
      containers:
        - name: pypiserver
          image: {{ .Values.image }}
          ports:
            - containerPort: 8080
              protocol: TCP
              name: http
          volumeMounts:
            - mountPath: /data/packages
              name: pypi-data
              subPath: packages
            - mountPath: /data/.htpasswd
              name: credentials
              subPath: access_file
              readOnly: true
