name: Main
on:
  push:
    branches: [ main ]
  pull_request: { }

jobs:
  build-container-image:
    needs:
      - lint
      - test
    uses: BlindfoldedSurgery/actions-container/.github/workflows/build-image-docker.yml@v2
    with:
      push-image: ${{ github.ref_name == github.event.repository.default_branch }}

  deploy:
    runs-on: ubuntu-latest
    needs: [ build-container-image ]
    if: success() && github.ref_name == github.event.repository.default_branch
    concurrency: production
    steps:
      - uses: actions/checkout@v4
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4
      - name: Substitute environment variables in values.yaml
        env:
          ACCESS_FILE_B64: ${{ secrets.ACCESS_FILE_B64 }}
          IMAGE_NAME: "ghcr.io/${{ env.GITHUB_REPOSITORY_OWNER_PART_SLUG }}/${{ env.GITHUB_REPOSITORY_NAME_PART_SLUG }}"
        run: "envsubst < values.yaml > values_sub.yaml && mv values_sub.yaml values.yaml"
      - uses: WyriHaximus/github-action-helm3@v3
        with:
          exec: |
            helm dependency update
            helm upgrade files . --install --namespace=pypi --atomic
          kubeconfig: '${{ secrets.KUBECONFIG_RAW }}'

  clean:
    concurrency: cleanup
    needs: [ deploy ]
    uses: BlindfoldedSurgery/actions-container/.github/workflows/clean.yml@v2
