name: Main
on:
  push:
    branches: [ main ]
  pull_request: { }

jobs:
  required-meta:
    uses: BlindfoldedSurgery/actions-meta/.github/workflows/required.yml@v1

  build-container-image:
    uses: preparingforexams/actions-container/.github/workflows/build-image-kaniko.yml@v5
    with:
      runner-name-build: warp-ubuntu-2404-arm64-2x
      push-image: ${{ github.ref_name == github.event.repository.default_branch }}

  deploy:
    runs-on: ubuntu-24.04
    if: github.ref_name == github.event.repository.default_branch
    needs:
      - build-container-image
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: git push origin main:release

  clean:
    concurrency: cleanup
    needs: [ deploy ]
    uses: preparingforexams/actions-container/.github/workflows/clean.yml@v5
