name: Main
on:
  push:
    branches: [ main ]
  pull_request: { }

jobs:
  validate-renovate-config:
    uses: BlindfoldedSurgery/renovate-config/.github/workflows/validate.yml@main

  build-container-image:
    uses: preparingforexams/actions-container/.github/workflows/build-image-kaniko.yml@v4
    with:
      runner-name-build: warp-ubuntu-latest-arm64-2x
      push-image: ${{ github.ref_name == github.event.repository.default_branch }}

  deploy:
    runs-on: ubuntu-latest
    if: github.ref_name == github.event.repository.default_branch
    needs:
      - build-container-image
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: git push origin main:release

  clean:
    concurrency: cleanup
    needs: [ deploy ]
    uses: BlindfoldedSurgery/actions-container/.github/workflows/clean.yml@v4
